### PR TITLE
Switch to extension registration mechanism

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #66  

This PR addresses or contains:
- Switches to extension registration mechanism
- Obsoletes https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/pull/58

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes: #66

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames I forgot this extension. I believe that this one should be cool without amending stuff. Keeping fingers crossed.

**Comment by kghbln** [comment]
The result is even worse that everything I did for the other two extensions before. Sad bunny.

**Comment by mwjames** [comment]
Actually, integration tests are failing (don't know why most likely due to MW version change, need to investigate but not this weekend).

```
There were 6 failures:
1) SIL\Tests\Integration\ParserFunctionIntegrationTest::testUseInterlanguageLinkParserInPage
SMW\Tests\Utils\Validators\SemanticDataValidator::assertContainsPropertyValues for '_SKEY' as '__key' with (en, Lorem ipsum, SIL\Tests\Integration\ParserFunctionIntegrationTest::testUseInterlanguageLinkParserInPage)
Failed asserting that an array contains 'SIL\Tests\Integration\ParserFunctionIntegrationTest::testUseInterlanguageLinkParserInPage#ill.en'.
```

**Comment by kghbln** [comment]
> Actually, integration tests are failing (don't know why most likely due to MW version change, need to investigate but not this weekend).

No worries. I have a total of three releases up next week which will keep me busy. I just figured the I should do it for this extension too.

**Pull request closed without merging**
