### PR TITLE
Now pt.json has all messages translated and pt-br just those different

### PR DESCRIPTION
**Pull request by jaideraf**
As @kghbln noted here https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/pull/16#issuecomment-69642465
I hope I did it right.

### CODE REVIEW

**Comment by jaideraf** [comment]
@kghbln Oh, right! I really forgot it. 
So what should I do now? I should correct my "repository" and send you another pull request?

**Comment by jaideraf** [comment]
@kghbln Oh, right! I really forgot it. 
So what should I do now? I should correct my "repository" and send you another pull request?

**Comment by kghbln** [comment]
Yeah, you can still edit your repo an update the current pull-request if I am not mistaken.

**Comment by mwjames** [comment]
> Yeah, you can still edit your repo an update the current pull-request if I am not mistaken.

In case you are using `git gui` you just have to check the `force` option. If you are not sure what to do or it seems to complicated then attach/upload the json files and we create a new PR.

git-force

**Comment by jaideraf** [comment]
Thanks @mwjames.
> In case you are using git gui you just have to check the force option.

I am using just the GitHub interface (just the web site).
I sent it again https://github.com/jaideraf/SemanticInterlanguageLinks/commit/921af3071443c990d7ea8f470d7a40a0b0e7489a

**Comment by mwjames** [comment]
@kghbln I needed to do a manual rebase therefore would be nice if you could double check i18n.

@jaideraf For future reference (not sure if one can do this with the GitHub interface) but before sending a PR it is general practice to rebase against the master in order to avoid to work on an outdated branch/fork [0]. If you are not able to manage a rebase, you might as well delete your fork and create a new one (it will pull automatically from the latest master).

[0] https://help.github.com/articles/syncing-a-fork/

**Comment by kghbln** [comment]
The files are ok. Thanks jaderaf for providing them and thanks to mwjames for supporting this effort.

**Comment by jaideraf** [comment]
Thanks @mwjames and @kghbln for the patience and for trying to teach me how to contribute by Git/GitHub.
As you can see, it’s not so easy for translators from translatewiki.net to go to every project in GitHub (or other means) and to translate the messages. So, I understand your frustration with Wikimedia permissions and other burocracies. But, we (just eventual translators) cannot help too much on these technical aspects.

**Pull request merged**
